### ISSUE TITLE
The bar with time period

### ISSUE THREAD

**Issue by fatality1922** [mateusz-bak/hejtter#10]
I think this bar takes a lot of useful space of the screen. Could be hidden while scrolling down and shown after scoll up.

I can work with isseus which I reported if you want me to contribute.
App looks really good and it's funny, but even now seems to he better than main competitor. 

![Screenshot_20230126_144541_Hejtter](https://user-images.githubusercontent.com/13122492/214852081-6e359f76-d4cb-4602-857a-1ff91b8bc465.jpg)

**Comment by mateusz-bak** [comment]
Planning to move the period button to AppBar like in Infinity for Reddit app.

Contact me in Hejto PM about collaboration. I have a Discord server.

And a little Kanban here: https://github.com/users/mateusz-bak/projects/3/views/1

**Comment by mateusz-bak** [comment]
Done, will be release in 0.0.15.
