### ISSUE TITLE
Color of the form results

### ISSUE THREAD

**Issue by fatality1922** [mateusz-bak/hejtter#9]
For now the results of the form has quite strange Color, brighter would be better for UX.
(of course I mean options which aren't choosen). 
 
![Screenshot_20230126_143408_Hejtter](https://user-images.githubusercontent.com/13122492/214849538-a42b761a-7d96-473e-9283-72959348a279.jpg)

**Comment by mateusz-bak** [comment]
Can you edit the screenshot (paint etc) with proposed colors?

**Comment by fatality1922** [comment]
I think something like this would be better 

![214849538-a42b761a-7d96-473e-9283-72959348a279](https://user-images.githubusercontent.com/13122492/215139341-e3c5a2c7-a0c0-4b08-ab8e-8b4a6ae80f69.jpg)

**Comment by mateusz-bak** [comment]
Done, voted option will be yellow, other ones bright blue. Will be in release 0.0.15.
